# This is a config for E2B sandbox template.
# You can use template ID (k6xumykrx3uankj3frrs) or template name (qckfx) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("qckfx") # Sync sandbox
# sandbox = await AsyncSandbox.create("qckfx") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('qckfx')

team_id = "f0c63627-e099-4318-bb31-a4066631cff7"
start_cmd = "/bin/bash"
dockerfile = "Dockerfile"
template_name = "qckfx"
template_id = "k6xumykrx3uankj3frrs"
